runtime: java
env: flex

runtime_config:
  operating_system: 'ubuntu22'
  runtime_version: '21'

env_variables:
  SPRINGBOOT_URL: 'https://split-smart-425113.as.r.appspot.com'
  SUPABASE_URL: 'https://hxhpgjrtbyeelougbebl.supabase.co'
  SUPABASE_KEY: ''
